# Generated by Django 3.2.4 on 2021-08-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('Course_code', models.CharField(max_length=10)),
                ('Course_schedule', models.FileField(upload_to='')),
                ('Syllabus', models.FileField(upload_to='')),
                ('Course_duration', models.CharField(max_length=10)),
                ('trainer_name', models.CharField(max_length=30)),
                ('time_in_hours', models.DurationField()),
            ],
        ),
    ]
