# Generated by Django 3.2.4 on 2021-09-23 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_img/925667.jpg', null=True, upload_to='profile_img'),
        ),
    ]
