# Generated by Django 3.2.4 on 2021-08-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
