# Generated by Django 3.2.4 on 2021-08-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Email_address',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Grade',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Guardian_name',
            new_name='guardian_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Medical_report',
            new_name='medical_report',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='National_Id',
            new_name='national_Id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Roll_number',
            new_name='roll_number',
        ),
        migrations.AlterField(
            model_name='student',
            name='languages',
            field=models.CharField(choices=[('k', 'kinyarwanda'), ('E', 'English'), ('L', 'Luganda'), ('k', 'kiswahili')], max_length=30),
        ),
    ]
