# Generated by Django 3.2.4 on 2021-08-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210820_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='medical_report',
            field=models.FileField(upload_to='uploads/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
